name: CI/CD - ASP.NET 8 to IIS on Windows VM

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to IIS locally
        shell: pwsh
        run: |
          Import-Module WebAdministration
          $sitePath = "C:\inetpub\wwwroot\GymManagement"
          Stop-WebAppPool -Name "GymManagement"
          Remove-Item "$sitePath\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path ".\publish\*" -Destination "$sitePath" -Recurse
          Start-WebAppPool -Name "GymManagement"
